# Generated by Django 3.1.12 on 2025-01-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
