# Generated by Django 3.1.12 on 2025-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
