# Generated by Django 3.1.12 on 2025-01-16 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0004_auto_20250116_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
