# Generated by Django 3.1.12 on 2025-01-16 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0005_auto_20250116_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
