# Generated by Django 3.1.12 on 2025-01-16 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0006_auto_20250116_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_year', models.IntegerField()),
                ('movie_rate', models.IntegerField()),
                ('movie_addeddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie_summary', models.TextField()),
            ],
        ),
    ]
