# Generated by Django 3.1.12 on 2025-01-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0007_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=80),
        ),
    ]
